controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: ['yaska1_joint_1_s', 'yaska1_joint_2_l', 'yaska1_joint_3_u', 'yaska1_joint_4_r', 'yaska1_joint_5_b', 'yaska1_joint_6_t']
