# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  end_effector_adaptater_mors2:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  end_effector_mors1:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.5
  yaska1_joint_1_s:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: true
    max_acceleration: 1.0
  yaska1_joint_2_l:
    has_velocity_limits: true
    max_velocity: 2.26892802759
    has_acceleration_limits: true
    max_acceleration: 1.0
  yaska1_joint_3_u:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 1.0
  yaska1_joint_4_r:
    has_velocity_limits: true
    max_velocity: 3.14159265359
    has_acceleration_limits: true
    max_acceleration: 1.0
  yaska1_joint_5_b:
    has_velocity_limits: true
    max_velocity: 4.36332312999
    has_acceleration_limits: true
    max_acceleration: 1.0
  yaska1_joint_6_t:
    has_velocity_limits: true
    max_velocity: 4.36332312999
    has_acceleration_limits: true
    max_acceleration: 1.0