controller_list:
  - name: DN2P1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - yaska1_joint_1_s
      - yaska1_joint_2_l
      - yaska1_joint_3_u
      - yaska1_joint_4_r
      - yaska1_joint_5_b
      - yaska1_joint_6_t
  - name: yaskawa1_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - end_effector_adaptater_mors2
      - end_effector_mors1